---
- name: Install pypackages
  hosts: all
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip


- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: template env_file
      template:
        src: templates/.env.j2
        dest: .env
        mode: 0664
      tags:
        - deploy


    - name: Deploy app
      community.docker.docker_container:
        name: redmine
        image: redmine:4.2
        state: started
        detach: yes
        ports:
          - "{{ redmine_app_port }}:3000"
        env_file: .env
      tags:
        - deploy


- name: Datadog http check
  hosts: webservers
  gather_facts: yes
  roles:
    - name: datadog.datadog