---
- name: Stop containers
  hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
      tags:
        - stop

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
      tags:
        - stop
